using System.Net;
using System.Text;

namespace StockApp.Infrastructure.Tests.TestDoubles;

/// <summary>
/// An <see cref="HttpMessageHandler"/> that answers with canned responses instead of using the network.
/// </summary>
/// <remarks>
/// Written by hand rather than generated by a mocking library: <see cref="SendAsync"/> is
/// <see langword="protected"/>, which mocking libraries handle awkwardly, and the whole double is
/// shorter than the setup code would be. Substituting the handler rather than the
/// <see cref="HttpClient"/> means the client under test is configured exactly as it is in production.
/// </remarks>
internal sealed class StubHttpMessageHandler(Func<HttpRequestMessage, HttpResponseMessage> respond)
    : HttpMessageHandler
{
    /// <summary>The last request the handler was asked to send, for asserting on the request shape.</summary>
    public HttpRequestMessage? LastRequest { get; private set; }

    /// <summary>Answers every request with <paramref name="response"/>.</summary>
    public StubHttpMessageHandler(HttpResponseMessage response)
        : this(_ => response)
    {
    }

    /// <summary>Answers with <paramref name="statusCode"/> and a JSON body.</summary>
    public static StubHttpMessageHandler Returning(HttpStatusCode statusCode, string json) =>
        new(Json(statusCode, json));

    /// <summary>Fails the way a transport-level problem does, before any response exists.</summary>
    public static StubHttpMessageHandler Throwing(Exception exception) =>
        new(_ => throw exception);

    /// <summary>Builds a JSON response, since every Yahoo reply is JSON regardless of status.</summary>
    public static HttpResponseMessage Json(HttpStatusCode statusCode, string json) =>
        new(statusCode)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json")
        };

    /// <inheritdoc />
    protected override Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
        LastRequest = request;

        // Real handlers observe cancellation, and the code under test distinguishes a caller
        // cancelling from an upstream timeout, so the double has to honour the token too.
        cancellationToken.ThrowIfCancellationRequested();

        return Task.FromResult(respond(request));
    }
}
